const {chromium}=require('C:/Users/gzfangyue/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const dir=path.join(__dirname,'evidence','v2');fs.mkdirSync(dir,{recursive:true});
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:'C:/Users/gzfangyue/AppData/Local/ms-playwright/chromium_headless_shell-1223/chrome-headless-shell-win64/chrome-headless-shell.exe'});
  const context=await browser.newContext({viewport:{width:1920,height:1080},deviceScaleFactor:1,recordVideo:{dir:path.join(dir,'recordings'),size:{width:1920,height:1080}}});
  const page=await context.newPage();const errors=[];const failed=[];
  page.on('pageerror',error=>errors.push(String(error)));
  page.on('requestfailed',request=>failed.push(request.url()));
  await page.goto('http://127.0.0.1:8786',{waitUntil:'networkidle'});
  await page.evaluate(()=>document.fonts.ready);
  await page.waitForTimeout(600);
  assert.equal(await page.locator('#region-name').textContent(),'北美禁区带');
  assert.equal(await page.locator('#enter').isEnabled(),true);
  const photo=await page.locator('#story-photo').evaluate(el=>({w:el.naturalWidth,h:el.naturalHeight,transform:getComputedStyle(el).transform}));
  assert.equal(photo.w,1104);assert.equal(photo.h,704);
  await page.screenshot({path:path.join(dir,'01-north-filled-1920x1080.png')});
  if(process.argv.includes('--first')){
    await context.close();await browser.close();process.stdout.write(JSON.stringify({photo,errors,failed}));return;
  }
  await page.waitForTimeout(900);
  await page.locator('.ticket[data-region=east]').hover();await page.waitForTimeout(450);
  await page.locator('.ticket[data-region=east]').click();await page.waitForTimeout(650);
  assert.equal(await page.locator('#region-name').textContent(),'东亚神秘地带');
  assert.equal(await page.locator('#enter').isDisabled(),true);
  assert.equal(await page.locator('#story-photo').getAttribute('src'),'assets/east.png');
  assert.equal(await page.locator('.map-place[data-region=east]').getAttribute('aria-pressed'),'true');
  await page.locator('#disclosure').click();await page.waitForTimeout(400);
  assert.equal(await page.locator('#disclosure').getAttribute('aria-expanded'),'true');
  assert.equal(await page.locator('#task-list').isVisible(),true);
  assert.equal(await page.locator('#deck').isVisible(),false);
  assert.match(await page.locator('#task-list').textContent(),/核对天文台基座位移/);
  await page.screenshot({path:path.join(dir,'02-east-locked-expanded-1920x1080.png')});
  await page.waitForTimeout(1100);
  await page.locator('.map-place[data-region=pacific]').click();await page.waitForTimeout(650);
  assert.equal(await page.locator('#region-name').textContent(),'南太平洋失航区域');
  assert.equal(await page.locator('#story-photo').getAttribute('src'),'assets/pacific.png');
  assert.match(await page.locator('#task-list').textContent(),/复听失联渔船呼号/);
  await page.keyboard.press('e');await page.waitForTimeout(350);
  assert.equal(await page.locator('#deck').isVisible(),true);
  await page.screenshot({path:path.join(dir,'03-pacific-filled-1920x1080.png')});
  await page.waitForTimeout(1000);
  await page.locator('.ticket[data-region=north]').click();await page.waitForTimeout(500);
  await page.locator('#disclosure').click();await page.waitForTimeout(650);
  await page.screenshot({path:path.join(dir,'04-north-expanded-1920x1080.png')});
  await page.waitForTimeout(750);
  await page.locator('#enter').click();await page.waitForTimeout(700);
  assert.equal(await page.locator('#entry-copy').isVisible(),true);
  assert.equal(await page.locator('#enter').textContent(),'返回选题桌 ↶');
  await page.waitForTimeout(1000);
  await page.keyboard.press('Escape');await page.waitForTimeout(350);
  assert.equal(await page.locator('#entry-copy').isVisible(),false);
  await page.keyboard.press('2');assert.equal(await page.locator('#enter').isDisabled(),true);
  await page.keyboard.press('3');assert.equal(await page.locator('#region-name').textContent(),'南太平洋失航区域');
  await page.keyboard.press('1');await page.waitForTimeout(700);
  const overflow=await page.evaluate(()=>[...document.querySelectorAll('.ticket strong,.ticket-hook,#deck,.task-name')].filter(el=>!el.hidden&&getComputedStyle(el).display!=='none'&&el.scrollWidth>el.clientWidth+1).map(el=>({text:el.textContent,width:el.clientWidth,scroll:el.scrollWidth})));
  assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);assert.deepEqual(overflow,[]);
  const video=page.video();
  const report={截图尺寸:[1920,1080],母图原始尺寸:[1104,704],检查:['三地区照片与文字同步','两处地区导航同步','锁定地区可阅读且进入禁用','任务信息原位展开与收起','切换地区后任务同步','较长地区名容纳','允许地区的样片入口反馈','Esc返回及数字键切换','无页面异常','无资源加载失败','受检文字无水平溢出'],页面错误:errors,加载失败:failed,溢出:overflow,边界:'独立浏览器美术样片；正式 Godot 与任务系统未连接。'};
  await context.close();
  const videoPath=await video.path();fs.copyFileSync(videoPath,path.join(dir,'05-interaction-demo.webm'));
  fs.writeFileSync(path.join(dir,'checks.json'),JSON.stringify(report,null,2),'utf8');
  await browser.close();process.stdout.write(JSON.stringify(report,null,2));
})().catch(error=>{process.stderr.write(String(error.stack));process.exit(1);});
